version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct

  - package-ecosystem: submodules
    directory: /
    schedule:
      interval: weekly
