[bump]
features_always_bump_minor = true
breaking_always_bump_major = true
initial_tag = "0.1.0"

[changelog]
header = """
# Changelog


"""

body = """
{% if version -%}
    <a name="{{ version | trim_start_matches(pat="v") }}"></a>

    {% if previous.version -%}
        ## [{{ version | trim_start_matches(pat="v") }}] ({{ timestamp | date(format="%Y-%m-%d") }})
    {% else -%}
        ## {{ version | trim_start_matches(pat="v") }} ({{ timestamp | date(format="%Y-%m-%d") }})
    {% endif -%}
{% else -%}
    ## [Unreleased]
{% endif -%}
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - \
        {% if commit.scope -%}
        **{{ commit.scope }}:** \
        {% endif -%}
        {{ commit.message | split(pat="\n") | first | upper_first | trim }} \
        {% if commit.links | length > 0 -%}
        (\
            {% for link in commit.links | unique(attribute="href") -%}
                [{{ link.text }}]({{ link.href }}){% if not loop.last %}, {% endif %}\
            {% endfor -%}
        ) \
        {% endif -%}
        ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/commit/{{ commit.id }}))\
    {% endfor %}
{% endfor %}


"""

footer = """
{% for release in releases -%}
    {% if release.version -%}
        {% if release.previous.version -%}
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}\
                    /compare/{{ release.previous.version }}..{{ release.version }}
        {% else -%}
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}\
                    /tree/{{ release.version }}
        {% endif -%}
    {% else -%}
        [unreleased]: https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}\
            /compare/{{ release.previous.version }}..HEAD
    {% endif -%}
{% endfor %}
<!-- generated by git-cliff -->
"""

trim = true

[git]
conventional_commits = true
filter_unconventional = false
commit_parsers = [
    { message = "^feat", group = "<!-- 0 --> Added" },
    { message = "^fix", group = "<!-- 1 --> Fixed" },
    { message = "^build\\(deps\\): bump actions/", skip = true },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^chore\\(version\\)", skip = true },
    { message = "^chore: bump version to", skip = true },
    { message = "^chore: update copyright year", skip = true },
    { message = "^ci:", skip = true },
    { message = "^docs", skip = true },
    { message = "^test:", skip = true },
]
protect_breaking_commits = true
filter_commits = false
tag_pattern = "v[0-9].*"
topo_order = false
sort_commits = "oldest"
link_parsers = [
    { pattern = "#(\\d+)", href = "https://github.com/tueda/makefile4latex/issues/$1" },
]
