default_install_hook_types: [pre-commit, commit-msg]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace

-   repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.3
    hooks:
    -   id: editorconfig-checker
        exclude: Makefile

-   repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.3
    hooks:
    -   id: editorconfig-checker
        name: editorconfig-checker (Makefile)
        files: Makefile
        args: [-disable-indentation]

-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.3
    hooks:
    -   id: check-github-workflows

-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
    -   id: gitlint
