language: generic
os:
  - linux
  - osx

git:
  depth: 1000

cache:
  directories:
    - $HOME/texlive

addons:
  apt:
    packages:
      - ghostscript

before_install:
  # Ghostscript on macOS
  - |
    if [ $TRAVIS_OS_NAME = osx ]; then
      brew install ghostscript
    fi
  # TeX Live
  - |
    case $TRAVIS_OS_NAME in
      linux)
        arch=x86_64-linux
        ;;
      osx)
        arch=x86_64-darwin
        ;;
    esac
  - |
    TEXLIVE_PATH=$HOME/texlive
    if [ ! -e $TEXLIVE_PATH/bin/$arch/tlmgr ]; then
      wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz -O - | tar -x --gzip
      echo "
      selected_scheme scheme-minimal
      TEXDIR $TEXLIVE_PATH
      TEXMFCONFIG ~/.texlive/texmf-config
      TEXMFHOME ~/texmf
      TEXMFLOCAL $TEXLIVE_PATH/texmf-local
      TEXMFSYSCONFIG $TEXLIVE_PATH/texmf-config
      TEXMFSYSVAR $TEXLIVE_PATH/texmf-var
      TEXMFVAR ~/.texlive/texmf-var
      collection-basic 1         # bibtex, dvipdfmx, makeindex, pdflatex
      collection-binextra 1      # latexdiff, latexpand
      collection-langjapanese 1  # jarticle.sty, platex
      collection-latexextra 1    # glossaries.sty, makeglossaries
      collection-plaingeneric 1  # ulem.sty
      collection-mathscience 1   # axodraw2.sty, axohelp
      collection-xetex 1         # xdvipdfmx
      option_doc 0
      option_src 0
      " | sed -e 's/^ *//' | sed -e 's/ *#.*$//' >texlive.profile
      ./install-tl-20*/install-tl --profile texlive.profile
      rm -rf texlive.profile install-tl-20*
    fi
  - export PATH=$TEXLIVE_PATH/bin/$arch:$PATH
  - tlmgr update --self
  # sortref: we also put it into the TeX Live directory.
  - |
    if [ ! -e $TEXLIVE_PATH/bin/$arch/sortref ]; then
      wget -O $TEXLIVE_PATH/bin/$arch/sortref https://web.physik.rwth-aachen.de/~harlander/software/sortref/sortref
      chmod +x $TEXLIVE_PATH/bin/$arch/sortref
    fi
  # Print LaTeX versions.
  - pdflatex --version
  - pdflatex-dev --version

script:
  - MAKE_COLORS=always MAKEFLAGS='' ./tests/check.sh -T
  - MAKE_COLORS=always MAKEFLAGS='BUILDDIR=build' ./tests/check.sh -T
  - MAKE_COLORS=always MAKEFLAGS='DEV=1' ./tests/check.sh -T
  - MAKE_COLORS=always MAKEFLAGS='DEV=1 BUILDDIR=build' ./tests/check.sh -T
  # Check if the working directory is not dirty.
  - git status && [ -z "$(git status --porcelain)" ]
